require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/account/users", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Account::User. As you add validations to Account::User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      first_name: "Blessed",
      last_name: "Sibanda",
      email: "blessed@example.com",
      date_of_birth: "15/08/1996",
      password: "my-secret",
      password_confirmation: "my-secret",
    }
  }

  let(:invalid_attributes) {
    {
      first_name: "Blessed",
      last_name: "Sibanda",
      email: "blessed@example.com",
      date_of_birth: "xxxxx",
      password: "my-secret",
      password_confirmation: "wrong-password",
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Account::User.create! valid_attributes
      get account_users_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user = Account::User.create! valid_attributes
      get account_user_url(user)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_account_user_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      user = Account::User.create! valid_attributes
      get edit_account_user_url(user)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Account::User" do
        expect {
          post account_users_url, params: { account_user: valid_attributes }
        }.to change(Account::User, :count).by(1)
      end

      it "redirects to the created account_user" do
        post account_users_url, params: { account_user: valid_attributes }
        expect(response).to redirect_to(account_user_url(Account::User.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Account::User" do
        expect {
          post account_users_url, params: { account_user: invalid_attributes }
        }.to change(Account::User, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post account_users_url, params: { account_user: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          first_name: "New Name",
          last_name: "Sibanda",
          email: "blessed@example.com",
          date_of_birth: "15/08/1996",
          password: "my-secret",
          password_confirmation: "my-secret",
        }
      }

      it "updates the requested account_user" do
        user = Account::User.create! valid_attributes
        patch account_user_url(user), params: { account_user: new_attributes }
        user.reload
        expect(user.first_name).to eq('New Name')
      end

      it "redirects to the account_user" do
        user = Account::User.create! valid_attributes
        patch account_user_url(user), params: { account_user: new_attributes }
        user.reload
        expect(response).to redirect_to(account_user_url(user))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        user = Account::User.create! valid_attributes
        patch account_user_url(user), params: { account_user: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested account_user" do
      user = Account::User.create! valid_attributes
      expect {
        delete account_user_url(user)
      }.to change(Account::User, :count).by(-1)
    end

    it "redirects to the account_users list" do
      user = Account::User.create! valid_attributes
      delete account_user_url(user)
      expect(response).to redirect_to(account_users_url)
    end
  end
end
